name: "Trigger: Push action" 
run-name: ${{ github.actor }} is running shellcheck
on:
  push:
    branches:
      - main

permissions: {}
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

