name: "Trigger: Pull request action"
run-name: ${{ github.actor }} is running write-good
on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  write-good:
    name: Write-good
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install write-good
        run: npm install -g write-good
      - name: Run write-good
        run: write-good '**/*.md' 
  
  
